#!/bin/bash

out=/srv/ipgem/reports
date="$( date +%F )"

/usr/libexec/ipgem-reports/load-report connections  >"$out/ipgem-connections-$date.csv"
/usr/libexec/ipgem-reports/load-report sources      >"$out/ipgem-sources-$date.csv"
/usr/libexec/ipgem-reports/load-report destinations >"$out/ipgem-destinations-$date.csv"
/usr/libexec/ipgem-reports/load-report todo         >"$out/ipgem-todo-$date.csv"

