#!/bin/bash

out=/srv/ipgem-rp
date="$( date +%F )"

/usr/lib/ipgem-rp/load-report connections  >"$out/ipgem-connections-$date.csv"
/usr/lib/ipgem-rp/load-report sources      >"$out/ipgem-sources-$date.csv"
/usr/lib/ipgem-rp/load-report destinations >"$out/ipgem-destinations-$date.csv"
/usr/lib/ipgem-rp/load-report todo         >"$out/ipgem-todo-$date.csv"

