#!/bin/bash

echo "Writing new IP configuration files."
ipgem-regen-ifcfg || exit $?

echo "Applying this configuration, there will be a slight interruption."
ipgem-ifdown
ipgem-ifup || exit $?

echo "Updating the iptables configuration."
ipgem-regen-iptables || exit $?

echo "OK."
