#!/bin/bash

set -e -u

. /etc/ipgem-gateway/networking

#cd /etc/sysconfig/network-scripts
#ls ifcfg-* |grep -vE "-$ADMIN_IFACE|-lo" |while read ifname; do
#	ifdown "$ifname"
#done

for iface in "${!IFNAME[@]}"; do
    ifdown "$iface"
done
